
hello_driving_pwm: hello_driving_pwm.o
	arm-linux-gcc hello_driving_pwm.o -o hello_driving_pwm

hello_driving_pwm.o: hello_driving_pwm.c
	arm-linux-gcc -c hello_driving_pwm.c

clean:
	rm *.o hello_driving_pwm
