#!/usr/bin/sh

# suppose running on /etc/init.d/S99_powersupply_pi

set -ex

cd /

rm -rf /root/.ssh
rm -rf /root/id_rsa
rm -rf /root/id_rsa.pub

ln -s /overlay/.ssh /root/.ssh
ln -s /overlay/.ssh/id_rsa /root/id_rsa
ln -s /overlay/.ssh/id_rsa.pub /root/id_rsa.pub

sync
