#!/bin/sh

start () {
  rm -rf /root/.ssh
  rm -rf /root/id_rsa
  rm -rf /root/id_rsa.pub

  ln -s /overlay/.ssh /root/.ssh
  ln -s /overlay/.ssh/id_rsa /root/id_rsa
  ln -s /overlay/.ssh/id_rsa.pub /root/id_rsa.pub

  sync
}

case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
