#!/bin/sh

start() {
  printf "Starting wifi"

  cd /overlay
    insmod r8723bs.ko
  cd -

  mkdir -p /lib/firmware/rtlwifi

  rm -rf /lib/firmware/rtlwifi/rtl8723bs_nic.bin
  ln -s   /overlay/rtl8723bs_nic.bin /lib/firmware/rtlwifi/rtl8723bs_nic.bin

  mv /etc/wpa_supplicant.conf /etc/wpa_supplicant.conf.buildroot
  ln -s /overlay/wpa_home/wpa_supplicant.conf /etc/wpa_supplicant.conf

  sync

  wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf

  # sleep 10

  # udhcpc -i wlan0

  ifconfig wlan0 192.168.99.250 netmask 255.255.255.0 up
  route add default gw 192.168.99.1
  echo "nameserver 192.168.99.1" > /etc/resolv.conf
}

case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
