#!/usr/bin/env sh

set -xe

echo "start wifi here"

insmod r8723bs.ko

mkdir -p /lib/firmware/rtlwifi

rm -rf /lib/firmware/rtlwifi/rtl8723bs_nic.bin
ln -s   /overlay/rtl8723bs_nic.bin /lib/firmware/rtlwifi/rtl8723bs_nic.bin

mv /etc/wpa_supplicant.conf /etc/wpa_supplicant.conf.buildroot
ln -s /overlay/wpa_home/wpa_supplicant.conf /etc/wpa_supplicant.conf

wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf

sleep 10

udhcpc -i wlan0

echo "done"