#!/bin/sh

start() {
  printf "Extracting react client"

  [ -d /tmp/www/cgi-bin ] || mkdir -p /tmp/www/cgi-bin

  cp -R /overlay/www/cgi-bin/* /tmp/www/cgi-bin

  unzip -o /overlay/react_client.zip -d /tmp/www

  sync

  echo "done"
}

stop() {
  echo "fallback uhttpd"
}

case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
