#!/bin/sh

start() {
  printf "Starting uhttpd"

  uhttpd -p 80 -h /tmp/www

  /overlay/utils/send_slack_httpd_started.sh

  sync

  # done
}

stop() {
  echo "S92_start_uhttpd stoping"

  echo "S92_start_uhttpd stopped"
}

case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
