#!/bin/sh
# suppose running on /etc/init.d/S99_powersupply_pi

start() {
  printf "Starting powersupply pi"
  /overlay/get_stat.sh > /overlay/stat.txt
  /overlay/utils/send_slack_module_ready.sh
  sync
}

stop() {
  echo "deinit powersupply pi"

  echo "deinit powersupply pi done"
}

case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
