#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu

# Install.
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y autoconf automake libtool gettext  && \
  apt-get install -y make gcc g++ swig python-dev bc python u-boot-tools bison flex bc libssl-dev libncurses5-dev unzip mtd-utils  && \
  apt-get install -y libc6-i386 lib32stdc++6 lib32z1  && \
  apt-get install -y libc6:i386 libstdc++6:i386 zlib1g:i386  && \
  apt-get install -y rsync cpio  && \
  apt-get install -y mtd-utils  && \
  apt-get install -y linux-headers-$(uname -r)  && \
  apt-get install -y vim && \
  rm -rf /var/lib/apt/lists/*

# Add files.
ADD root/.bashrc /root/.bashrc
ADD root/.gitconfig /root/.gitconfig
ADD root/.scripts /root/.scripts

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
